version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-ts-app
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
